In [44]:
import pandas
file = pandas.read_csv("C:\\Users\\b1070\\Desktop\\AI100\\data\\application_train.csv")

資料的 row 數以及 column 數

In [45]:
rows = file.shape[0]
columns = file.shape[1]
print("row: {0}\ncolumns: {1}".format(rows, columns))

row: 307511
columns: 122

列出所有欄位

In [51]:
file.head(rows)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
218731,353408,0,Revolving loans,F,N,Y,1,135000.0,405000.0,20250.0,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,4.0
138241,260313,0,Revolving loans,M,Y,Y,2,126000.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
225783,361516,0,Revolving loans,F,N,Y,0,292500.0,585000.0,29250.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
9580,111135,0,Revolving loans,M,Y,Y,1,292500.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
296899,443975,0,Revolving loans,F,Y,Y,0,180000.0,360000.0,18000.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,3.0
296896,443971,0,Revolving loans,M,Y,Y,0,247500.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
9583,111138,0,Revolving loans,M,N,Y,1,135000.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
9585,111140,0,Revolving loans,F,N,Y,0,81000.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
73854,185654,0,Revolving loans,M,Y,Y,1,135000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
73852,185652,0,Revolving loans,F,Y,Y,0,247500.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
225792,361526,0,Revolving loans,M,N,N,0,162000.0,900000.0,45000.0,...,0,0,0,0,0.0,0.0,0.0,1.0,2.0,7.0
9592,111149,0,Revolving loans,M,N,Y,1,112500.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
296885,443959,0,Revolving loans,F,N,N,2,135000.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
138227,260298,0,Revolving loans,M,N,Y,0,315000.0,1350000.0,67500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
296877,443951,0,Revolving loans,M,Y,Y,0,225000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
138221,260292,0,Revolving loans,F,N,Y,0,90000.0,247500.0,12375.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
85479,199188,1,Revolving loans,F,N,Y,0,157500.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
154712,279331,0,Revolving loans,F,N,Y,0,67500.0,337500.0,16875.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,5.0
9606,111163,0,Revolving loans,F,N,Y,1,72000.0,225000.0,11250.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
9610,111170,0,Revolving loans,M,N,Y,1,90000.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
85485,199194,0,Revolving loans,F,N,Y,0,90000.0,225000.0,11250.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
85510,199221,0,Revolving loans,F,N,Y,0,49500.0,135000.0,6750.0,...,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
154760,279388,0,Revolving loans,F,N,Y,0,90000.0,202500.0,10125.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,3.0
154761,279389,1,Revolving loans,F,N,Y,0,90000.0,202500.0,10125.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0
85541,199260,0,Revolving loans,F,N,Y,0,540000.0,1350000.0,67500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
296742,443799,0,Revolving loans,M,N,Y,0,157500.0,225000.0,11250.0,...,0,0,0,0,0.0,0.0,0.0,14.0,0.0,0.0
85546,199267,0,Revolving loans,M,N,Y,0,189000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
296904,443980,0,Revolving loans,M,Y,Y,0,157500.0,337500.0,16875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
154686,279303,0,Revolving loans,F,Y,N,1,157500.0,450000.0,22500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
225766,361496,0,Revolving loans,F,N,N,0,112500.0,337500.0,16875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291695,437926,0,Cash loans,F,Y,N,0,112500.0,305221.5,15633.0,...,1,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
291696,437927,0,Cash loans,M,N,N,0,180000.0,288873.0,19435.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
291697,437928,0,Cash loans,M,Y,Y,0,315000.0,1312110.0,48753.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
291698,437929,0,Cash loans,M,Y,N,1,157500.0,314055.0,17167.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
291645,437868,0,Cash loans,F,Y,N,2,337500.0,526491.0,28179.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
291643,437866,0,Cash loans,M,N,Y,0,135000.0,152820.0,15016.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
291641,437864,0,Cash loans,F,N,Y,0,112500.0,265851.0,14548.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
291594,437807,0,Cash loans,F,N,N,0,117000.0,269550.0,13095.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,7.0
291587,437799,0,Cash loans,M,Y,N,2,180000.0,292500.0,18022.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
291588,437800,1,Cash loans,F,N,Y,1,81000.0,284400.0,13387.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
291590,437802,0,Cash loans,M,Y,N,1,180000.0,631332.0,45940.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
291690,437920,0,Cash loans,F,N,Y,0,112500.0,390960.0,17352.0,...,0,0,0,0,0.0,0.0,0.0,1.0,3.0,8.0
291689,437919,0,Cash loans,F,Y,Y,0,202500.0,599472.0,36805.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
291688,437917,1,Cash loans,M,N,N,0,315000.0,1971072.0,68643.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
291717,437951,1,Cash loans,M,N,N,0,157500.0,540000.0,30280.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
291711,437944,0,Cash loans,F,Y,N,0,135000.0,677664.0,24471.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
291701,437932,0,Cash loans,F,N,N,0,369000.0,706410.0,67203.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
291712,437946,0,Cash loans,F,N,Y,0,135000.0,1381113.0,37980.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
291713,437947,0,Cash loans,F,N,Y,0,112500.0,242595.0,18904.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
291714,437948,0,Cash loans,M,Y,Y,2,157500.0,797557.5,28777.5,...,0,0,0,0,0.0,0.0,0.0,4.0,2.0,1.0
291715,437949,0,Cash loans,F,N,Y,1,139500.0,355536.0,19287.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
291718,437952,0,Cash loans,F,N,Y,1,90000.0,161730.0,12829.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
291687,437916,0,Cash loans,F,N,N,0,76500.0,269550.0,11416.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
291702,437934,0,Cash loans,F,Y,N,0,225000.0,450000.0,53536.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
291700,437931,0,Cash loans,M,Y,Y,0,202500.0,838453.5,42939.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
291684,437912,0,Cash loans,F,N,Y,0,189000.0,247500.0,12037.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
291691,437921,0,Cash loans,M,N,Y,1,180000.0,592560.0,40216.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
291685,437914,0,Cash loans,M,Y,N,1,135000.0,1078200.0,31653.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,7.0
291686,437915,0,Cash loans,F,N,Y,0,121500.0,473841.0,27333.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
55721,164561,0,Cash loans,F,N,Y,2,90000.0,770292.0,30676.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0

擷取部分資料

In [52]:
file[['CODE_GENDER','FLAG_OWN_CAR']][0:5]

       CODE_GENDER FLAG_OWN_CAR
218731           F            N
138241           M            Y
225783           F            N
9580             M            Y
296899           F            Y